### ISSUE TITLE
lazy inject 不能处理 handler 以及原始值类型

### ISSUE THREAD

**Issue by JerrysShan** [artusjs/injection#57]
现有 lazy 的实现遇到下面两个问题，需要重构 lazy 的实现方式：
1. 采用 proxy 的方式，无法处理原始值类型，比如注入的值是字符串，无法 proxy

解决方案是采用 `getter`，虽然会改变属性的原始定义语义

2. 现在 lazy 采用了 handler 处理，如果注入的属性，是一个自定义的 handler ，会有报错

**重构后，lazy inject 不能通过构造函数参数注入**

**Comment by JerrysShan** [comment]
我们遇到在 lifecycle 里面注入 config 值的时候，遇到了这种场景

**Comment by hyj1991** [comment]
`config` 其实可以单独处理下，loader 启动前配置一个空对象，这样就不需要使用 lazy 了

**Comment by JerrysShan** [comment]
还不太一样，主要是为了保持使用方式一致

```typescript
@LifecycleHookUnit()
export default class MyLifecycle implements ApplicationLifecycle {
  @Config('name')
  name: string;

  @LifecycleHook()
  public didLoad() {
    console.log(this.config);
  }
}


```
